export const portfolioData = [
   {   
      id: 1,
      name: 'BudgetFM',
      category: 'Full Stack Application',
      image: 'https://i.ibb.co/1MtsmBC/Screen-Shot-2020-01-11-at-11-52-04-PM.jpg',
      description: 'Robust budgeting tool that allows the client to track and manage their monthly income and expenses while monitoring and updating the total balance accordingly',
      technologies: 'React Hooks, Context API, Express, Formik',
      walkthrough: 'https://vimeo.com/385726910',
      github:  'https://github.com/jordanutz/BudgetFM', 
      portfolio: false
  }, 
  {
      id: 2,
      name: 'Kalwaii',
      category: 'Full Stack Application',
      image: 'https://i.ibb.co/Brr8nTH/Screen-Shot-2020-01-12-at-5-47-37-PM.jpg',
      description: 'Emulates the core functionality of MyFitnessPal, where client can track their calories each day and create meal plans that align with their dietary goals',
      technologies: 'React, Redux, Sass, Express, Chart.js, AntDesign',
      walkthrough: 'https://vimeo.com/385726508',
      github: 'https://github.com/jordanutz/Kalwaii', 
      portfolio: false
  },
  {
      id: 3,
      name:  'PokeFlex',
      category:  'Full Stack Application',
      image: 'https://i.ibb.co/WV9Z2P1/Screen-Shot-2020-01-15-at-9-30-56-PM.jpg',
      description: 'Application for strategizing and building a competitive Pokemon team',
      technologies: 'React, Redux, Radium, Express',
      walkthrough: 'https://vimeo.com/385726984',
      github: 'https://github.com/jordanutz/PokeFlex', 
      portfolio: false
  },
  {
      id: 4,
      name: 'Bikevana',
      category: 'Full Stack Application',
      image: 'https://i.ibb.co/HV03DWQ/Screen-Shot-2020-01-16-at-10-11-47-PM.jpg',
      description: 'Cloned project of Carvana that can be used to search for bicycles and make a purchase through a registered account utilizing the Stripe API',
      technologies: 'React, Redux, Stripe API, Express',
      walkthrough: '',
      github: 'https://github.com/jordanutz/BikeVana', 
      portfolio: false
  },
  {
      id: 5,
      name: 'Spookr',
      category: 'Full Stack Application',
      image: 'Group',
      description: 'Full stack application in the style of Tinder that provides a platform where ghosts and homeowners can network to find their perfect haunting',
      technologies: 'React, Redux, Node.js, Express, Sass, Socket.io, React-Geocode',
      walkthrough: 'https://vimeo.com/386631424',
      github:  'https://github.com/spookr/Spookr',
      portfolio: false
  },
//   {
//       id: 6,
//       name: 'WeatherFi',
//       category: 'Full Stack Application',
//       image: 'Personal',
//       description: 'DarkSky API coupled with Axios to generate the 5-day weather forecast when the user provides a city and state in the United States',
//       technologies:  'React, DarkSky API, Axios, Node.js, Express',
//       walkthrough: 'https://vimeo.com/386634167',
//       github: 'https://github.com/jordanutz/AwesomeWeather', 
//       portfolio: true
//   },
  {
      id: 7,
      name: 'myAmiibo', 
      category: 'Full Stack Application',
      image: 'Personal',
      description:  'Environment in which no database is implemented but data extracted from the AmiiboAPI persists when character is selected and assigned to team',
      technologies: 'React, Amiibo API, Axios, Node.js, Express',
      walkthrough: '',
      github: 'https://github.com/jordanutz/AmiiboSmash', 
      portfolio: false
  }, 
  {
    id: 8,
    name: 'Quiz Time: Video Game Ed.',
    category: 'Project Highlight',
    year: '2021',
    image: 'https://i.ibb.co/hWssRWD/Screen-Shot-2021-02-18-at-1-41-32-PM.jpg',
    description: 'Intuitive trivia game that tests players of their knowledge of video games with a set of randomized questions retrieved from the Open Trivia API, alerting the player if their selection is correct or incorrect through visual cues and tracking their progress with each question',
    walkthrough: null,
    technologies: 'React, JavaScript, Axios, Sass, Open Trivia API',
    github: 'https://github.com/jordanutz/quiz-time',
    codepen: 'https://codepen.io/jordanutz/pen/mdOPWpE', 
    portfolio: true
 },
 {
    id: 9,
    name: 'Calculator',
    category: 'Project Highlight',
    year: '2021',
    image: ' https://i.ibb.co/3TcDqS7/Screen-Shot-2021-02-18-at-6-55-40-PM-2.jpg',
    description: 'JavaScript powered calculator with a stylish interface. Typescript also leveraged for explicit static typing of data scoped to the user input that is captured and rendered to the display, and the expressions that are evaluated when an operant is selected',
    walkthrough: null,
    technologies: 'React, JavaScript, TypeScript, Sass',
    github: 'https://github.com/jordanutz/react-calculator',
    codepen: 'https://codepen.io/jordanutz/pen/vYyZrwb', 
    portfolio: true
 },
];